import { STORAGE_INDEXES } from "."

export const USERS_PRM={
    ROWS_PER_PAGE_OPTIONS:[5,10,25,50,100],
    ROWS_PER_PAGE:{KEY:STORAGE_INDEXES.NUMBER_OF_ROWS, VALUE:10},
    PAGE_NO:{KEY:STORAGE_INDEXES.PAGE_NO, VALUE:0},
    ROLE_ID:{KEY:STORAGE_INDEXES.ROLE_ID, VALUE:null},
    SEARCH_TEXT:{KEY:STORAGE_INDEXES.SEARCH_TEXT, VALUE:""},
}

export const COMMON_PAGINATION={
    ROWS_PER_PAGE_OPTIONS:[5,10,25,50,100],
    ROWS_PER_PAGE:{KEY:STORAGE_INDEXES.NUMBER_OF_ROWS, VALUE:10},
    PAGE_NO:{KEY:STORAGE_INDEXES.PAGE_NO, VALUE:0},
    ROLE_ID:{KEY:STORAGE_INDEXES.ROLE_ID, VALUE:null},
    SEARCH_TEXT:{KEY:STORAGE_INDEXES.SEARCH_TEXT, VALUE:""},
    FILTER_STATUS:{KEY:STORAGE_INDEXES.FILTER_STATUS, VALUE:""},
}

export const BLOG_PAGINATION={
    ROWS_PER_PAGE_OPTIONS:[5,10,25,50,100],
    ROWS_PER_PAGE:{KEY:STORAGE_INDEXES.NUMBER_OF_ROWS, VALUE:10},
    PAGE_NO:{KEY:STORAGE_INDEXES.PAGE_NO, VALUE:0},
    STATUS:{KEY:'status', VALUE:null},
    SEARCH_TEXT:{KEY:STORAGE_INDEXES.SEARCH_TEXT, VALUE:""},
}
export const POST_PAGINATION={
    ROWS_PER_PAGE_OPTIONS:[5,10,25,50,100],
    ROWS_PER_PAGE:{KEY:STORAGE_INDEXES.NUMBER_OF_ROWS, VALUE:10},
    PAGE_NO:{KEY:STORAGE_INDEXES.PAGE_NO, VALUE:0},
    STATUS:{KEY:'status', VALUE:null},
    SEARCH_TEXT:{KEY:STORAGE_INDEXES.SEARCH_TEXT, VALUE:""},
}