const blocks = {
  struct: {
    tiles: {
      tileList: [
        {
          id: "kiee3c",
          color: null,
          quest: "Question 1",
          password: "Correct Answer 1",
          buttonLink: "",
          buttonText: "",
          overlaySrc: "",
          headerImgSrc: "",
          questDescription: "",
        },
        {
          id: "adbman",
          color: null,
          quest: "Question 2",
          password: "Correct Answer 2",
          buttonLink: "",
          buttonText: "",
          overlaySrc: "",
          headerImgSrc: "",
          questDescription: "",
        },
        {
          id: "juchp9",
          color: null,
          quest: "Question 3",
          password: "Correct Answer 3",
          buttonLink: "",
          buttonText: "",
          overlaySrc: "",
          headerImgSrc: "",
          questDescription: "",
        },
        {
          id: "7ygy1q",
          color: null,
          quest: "Question 4",
          password: "Correct Answer 4",
          buttonLink: "",
          buttonText: "",
          overlaySrc: "",
          headerImgSrc: "",
          questDescription: "",
        },
      ],
    },
    playground: {
      layout: {
        cols: 2,
        rows: 2,
        label: "2x2",
        value: 4,
      },
      coverPosition: "center",
      cardProportions: "1:1",
      isShowQuestCover: false,
    },
    finalScreen: {
      header: "Congrats message",
      imageSrc: "",
      description: "Description",
      imageDisclaimer: "",
    },
  },
  colorTheme: "#20a2b8",
  yandexMetric: {
    CTA_CLICK: "",
    GAME_OPENED: "",
    GAME_STARTED: "",
    SEC_IN_GAME_5: "",
    GAME_COMPLETED: "",
    GAME_RESTARTED: "",
    SEC_IN_GAME_10: "",
    LEAD_FORM_SUBMITTED: "",
  },
  isActionButton: false,
  isShowLeadForm: false,
  leadFormStruct: {
    form: {
      fields: [
        {
          key: "firstName",
          label: "First name",
          isRequired: true,
        },
        {
          key: "email",
          label: "Email",
          isRequired: true,
        },
      ],
      logoImage: "",
      buttonText: "Submit",
      headerText: "Form",
      descriptionText: "Please fill in the form fields",
      linkPrivacyPolicyLink: "",
    },
    isHasFinalScreen: false,
  },
  redirectTimeout: 4,
  actionButtonLink: "",
  actionButtonText: "",
  isRedirectEnabled: false,
  leadFormFontFamily: "Roboto",
  redirectTargetLink: "",
  isHideRestartButton: false,
  leadFormBackgroundColor: "#fff",
};
