export const SELECTED = "SELECTED";
export const SELECTED_SUCCESS = "SELECTED_SUCCESS";
export const GET_TEMPLATE_DETAILS_REQUEST = "GET_TEMPLATE_DETAILS_REQUEST";
export const GET_TEMPLATE_DETAILS_SUCCESS = "GET_TEMPLATE_DETAILS_SUCCESS";
export const UPDATE = "UPDATE";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
